services:
  mysql:
    image: mysql:8.4
    container_name: nailsbyjess-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - nailsbyjess-db:/var/lib/mysql

volumes:
  nailsbyjess-db: